# Generated by Django 4.2.7 on 2023-11-28 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateDeNaissance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='motDePasse',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
