# Generated by Django 4.2.7 on 2023-11-28 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.AddField(
            model_name='activity',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idActivity',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
