# Generated by Django 4.2.7 on 2023-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0004_remove_activity_id_activity_datecreation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='idActivity',
        ),
        migrations.AddField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
