# Generated by Django 4.2.7 on 2023-11-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0005_remove_activity_idactivity_activity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityTracker.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Gylocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('heading', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitudeAccuracy', models.FloatField()),
                ('latitude', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityTracker.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityTracker.activity')),
            ],
        ),
    ]
