# Generated by Django 4.2.7 on 2023-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0006_gyroscope_gylocation_acceleration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='etiquette',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
