# Generated by Django 4.2.7 on 2023-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0007_activity_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
