# Generated by Django 4.2.7 on 2023-11-30 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0008_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateConnxion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
