# Generated by Django 4.2.7 on 2023-11-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0009_user_dateconnxion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateConnxion',
            new_name='dateConnexion',
        ),
    ]
