# Generated by Django 4.2.7 on 2023-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityTracker', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
